### ISSUE TITLE
Hi Professor Weber. Great class, but so far no content in this repository

### ISSUE THREAD

**Issue by barlaensdoonn** [nniiicc/LIS-598-Wi2020-DigitalPreservation#1]
Would be great to have this repo filled out and preserved "for all of eternity without a worry in the world because it's hosted by the world class organization GitHub" =]

But in all seriousness, maybe this would make a good summer project to fill out. I'd be happy to help around then, I'm pretty busy this quarter with a DFW and two classes plus work.

**Comment by nniiicc** [comment]
@barlaensdoonn - You can download a zip with all the class content here https://drive.google.com/file/d/1o9YOXn1H4jwMlllbjje2O6bEtXeTFj4n/view (you need to login with your UW email account) ... I don't have this repository set up to have enough storage space for the lecture videos.

**Comment by barlaensdoonn** [comment]
thxx!! 🙌
